# ***************************************************************
# Copyright (c) 2023 Jittor. All Rights Reserved.
# Maintainers: Jittor Group
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.
# ***************************************************************
# Native jt.Generator (src/runtime/random_generator.{h,cc}): an independent,
# device-native RNG state a caller can create/seed/save/restore, separate
# from the single global RNG stream that ordinary jt.random()/jt.randn()/etc.
# draw from. This repo previously had no such thing -- only a torch-compat,
# numpy-backed shim in compat/torch, disconnected from native RNG entirely.
#
# On CUDA, a jt.Generator("cuda") is a counter-based Philox stream keyed by
# its seed: (seed, position) is its complete state, generated by jittor's own
# kernel through the curand device API, independent of the per-device global
# generator every other draw shares. A draw reserves its positions when it is
# built, so get_state() covers every draw issued before it, executed or not.
# (The CPU generator still advances when a draw executes.)
import unittest

import numpy as np

import jittor as jt
from _helpers import capability as _test_capability

_has_cuda = _test_capability.check_accelerator("cuda", backend=jt).enabled


class TestRandomGenerator(unittest.TestCase):
    def test_seeded_reproducible_cpu(self):
        g1 = jt.Generator("cpu").manual_seed(42)
        g2 = jt.Generator("cpu").manual_seed(42)
        a = jt.random((8,), generator=g1).numpy()
        b = jt.random((8,), generator=g2).numpy()
        np.testing.assert_array_equal(a, b)

    def test_different_seed_differs_cpu(self):
        g1 = jt.Generator("cpu").manual_seed(1)
        g2 = jt.Generator("cpu").manual_seed(2)
        a = jt.random((8,), generator=g1).numpy()
        b = jt.random((8,), generator=g2).numpy()
        self.assertFalse(np.allclose(a, b))

    def test_independent_generators_do_not_perturb_each_other(self):
        g1 = jt.Generator("cpu").manual_seed(7)
        g2 = jt.Generator("cpu").manual_seed(123)
        baseline = jt.random((5,), generator=g1).numpy()

        g1b = jt.Generator("cpu").manual_seed(7)
        interleaved = []
        for _ in range(5):
            jt.random((1,), generator=g2).sync()
            interleaved.append(jt.random((1,), generator=g1b).numpy()[0])
        np.testing.assert_allclose(baseline, np.array(interleaved))

    def test_generator_does_not_perturb_global_stream(self):
        jt.set_seed(0)
        before = jt.random((4,)).numpy()

        jt.set_seed(0)
        g = jt.Generator("cpu").manual_seed(999)
        jt.random((4,), generator=g).sync()  # drawn from g, not the global stream
        after = jt.random((4,)).numpy()
        np.testing.assert_array_equal(before, after)

    def test_state_roundtrip_cpu(self):
        g = jt.Generator("cpu").manual_seed(5)
        jt.random((6,), generator=g).sync()
        state = g.get_state()
        a = jt.random((6,), generator=g).numpy().copy()
        g.set_state(state)
        b = jt.random((6,), generator=g).numpy().copy()
        np.testing.assert_array_equal(a, b)

    def test_initial_seed_and_reseed(self):
        g = jt.Generator("cpu").manual_seed(17)
        self.assertEqual(g.initial_seed(), 17)
        new_seed = g.seed()
        self.assertEqual(g.initial_seed(), new_seed)

    def test_device_property(self):
        g = jt.Generator("cpu")
        self.assertEqual(g.device, "cpu")


class TestRandomGeneratorCuda(unittest.TestCase):
    @unittest.skipIf(not _has_cuda, "No cuda found")
    @jt.flag_scope(use_cuda=1)
    def test_seeded_reproducible_cuda(self):
        g1 = jt.Generator("cuda").manual_seed(42)
        g2 = jt.Generator("cuda").manual_seed(42)
        a = jt.random((6,), generator=g1).numpy()
        b = jt.random((6,), generator=g2).numpy()
        np.testing.assert_allclose(a, b)

    @unittest.skipIf(not _has_cuda, "No cuda found")
    @jt.flag_scope(use_cuda=1)
    def test_different_seed_differs_cuda(self):
        g1 = jt.Generator("cuda").manual_seed(42)
        g2 = jt.Generator("cuda").manual_seed(99)
        a = jt.random((6,), generator=g1).numpy()
        b = jt.random((6,), generator=g2).numpy()
        self.assertFalse(np.allclose(a, b))

    @unittest.skipIf(not _has_cuda, "No cuda found")
    @jt.flag_scope(use_cuda=1)
    def test_uniform_state_roundtrip_cuda(self):
        g = jt.Generator("cuda").manual_seed(5)
        jt.random((7,), generator=g).sync()
        state = g.get_state()
        a = jt.random((7,), generator=g).numpy().copy()
        g.set_state(state)
        b = jt.random((7,), generator=g).numpy().copy()
        np.testing.assert_allclose(a, b)

    @unittest.skipIf(not _has_cuda, "No cuda found")
    @jt.flag_scope(use_cuda=1)
    def test_normal_odd_length_state_roundtrip_cuda(self):
        # curandGenerateNormal requires an even count; an odd-length draw
        # takes its last element from a separate two-element scratch buffer
        # (see curand_random_op.cc). Regression coverage for that split
        # path's offset bookkeeping specifically.
        g = jt.Generator("cuda").manual_seed(5)
        jt.random((7,), dtype="float32", type="normal", generator=g).sync()
        state = g.get_state()
        a = jt.random((7,), dtype="float32", type="normal", generator=g).numpy().copy()
        g.set_state(state)
        b = jt.random((7,), dtype="float32", type="normal", generator=g).numpy().copy()
        np.testing.assert_allclose(a, b)

    @unittest.skipIf(not _has_cuda, "No cuda found")
    @jt.flag_scope(use_cuda=1)
    def test_normal_even_length_state_roundtrip_cuda(self):
        g = jt.Generator("cuda").manual_seed(5)
        jt.random((8,), dtype="float32", type="normal", generator=g).sync()
        state = g.get_state()
        a = jt.random((8,), dtype="float32", type="normal", generator=g).numpy().copy()
        g.set_state(state)
        b = jt.random((8,), dtype="float32", type="normal", generator=g).numpy().copy()
        np.testing.assert_allclose(a, b)

    @unittest.skipIf(not _has_cuda, "No cuda found")
    @jt.flag_scope(use_cuda=1)
    def test_generator_does_not_perturb_global_cuda_stream(self):
        d1 = jt.random((4,)).numpy()
        g = jt.Generator("cuda").manual_seed(999)
        jt.random((4,), generator=g).sync()
        d2 = jt.random((4,)).numpy()
        self.assertEqual(d1.shape, d2.shape)


@unittest.skipIf(not _has_cuda, "No cuda found")
class TestRandomGeneratorCudaCheckpoint(unittest.TestCase):
    """Non-zero CUDA states replay exactly (jittor-core-gaps.md §3.3).

    The old generator kept a curand host-API generator and restored it with
    curandSetGeneratorOffset. The host API does not continue a stream the way
    a fresh generator at the summed offset does, so these replays diverged
    completely for float64 and for normal draws at 65536 samples.
    """
    CASES = [(dtype, dist) for dtype in ("float32", "float64")
             for dist in ("uniform", "normal")]

    @staticmethod
    def _draw(g, n, dtype, dist):
        return jt.random((n,), dtype=dtype, type=dist, generator=g)

    @jt.flag_scope(use_cuda=1)
    def test_large_nonzero_state_restore(self):
        for dtype, dist in self.CASES:
            for first, second in ((65536, 65536), (65537, 1001), (5, 7), ((1 << 20) + 2, 4099)):
                g = jt.Generator("cuda").manual_seed(59)
                self._draw(g, first, dtype, dist).sync()
                state = g.get_state()
                natural = self._draw(g, second, dtype, dist).numpy().copy()
                g.set_state(state)
                restored = self._draw(g, second, dtype, dist).numpy()
                np.testing.assert_array_equal(
                    restored, natural, err_msg="%s %s %d->%d" % (dtype, dist, first, second))

    @jt.flag_scope(use_cuda=1)
    def test_state_covers_draws_that_have_not_executed(self):
        for dtype, dist in self.CASES:
            g = jt.Generator("cuda").manual_seed(59)
            pending = self._draw(g, 65536, dtype, dist)       # not synced
            state = g.get_state()
            natural = self._draw(g, 4096, dtype, dist).numpy().copy()
            pending.sync()
            g.set_state(state)
            np.testing.assert_array_equal(
                self._draw(g, 4096, dtype, dist).numpy(), natural, err_msg="%s %s" % (dtype, dist))

    @jt.flag_scope(use_cuda=1)
    def test_consecutive_draws_continue_one_stream(self):
        # Each draw consumes exactly what it reserved: two draws are the two
        # halves of one draw, so consecutive draws never overlap.
        for dtype, dist in self.CASES:
            for n1, n2 in ((6, 10), (4096, 12), (1 << 20, 1000)):
                whole = self._draw(jt.Generator("cuda").manual_seed(3), n1 + n2, dtype, dist).numpy()
                g = jt.Generator("cuda").manual_seed(3)
                parts = np.concatenate([self._draw(g, n1, dtype, dist).numpy(),
                                        self._draw(g, n2, dtype, dist).numpy()])
                np.testing.assert_array_equal(parts, whole, err_msg="%s %s %d+%d" % (dtype, dist, n1, n2))

    @jt.flag_scope(use_cuda=1)
    def test_distribution_moments(self):
        for dtype, dist in self.CASES:
            x = self._draw(jt.Generator("cuda").manual_seed(8), 1 << 22, dtype, dist).numpy()
            self.assertEqual(str(x.dtype), dtype)
            if dist == "uniform":
                self.assertTrue(x.min() > 0 and x.max() <= 1)
                self.assertAlmostEqual(float(x.mean()), 0.5, delta=2e-3)
                self.assertAlmostEqual(float(x.var()), 1 / 12, delta=2e-3)
            else:
                self.assertAlmostEqual(float(x.mean()), 0.0, delta=3e-3)
                self.assertAlmostEqual(float(x.var()), 1.0, delta=5e-3)
            self.assertLess(abs(np.corrcoef(x[:-1], x[1:])[0, 1]), 3e-3)

    @jt.flag_scope(use_cuda=1)
    def test_draw_outlives_its_generator(self):
        g = jt.Generator("cuda").manual_seed(4)
        pending = jt.random((1000,), generator=g)
        del g
        expect = jt.random((1000,), generator=jt.Generator("cuda").manual_seed(4)).numpy()
        np.testing.assert_array_equal(pending.numpy(), expect)

    def test_state_from_another_device_is_rejected(self):
        cpu_state = jt.Generator("cpu").manual_seed(1).get_state()
        cuda = jt.Generator("cuda").manual_seed(2)
        before = cuda.get_state()
        with self.assertRaisesRegex(RuntimeError, "belongs to"):
            cuda.set_state(cpu_state)
        self.assertEqual(cuda.get_state(), before)

    def test_old_cuda_state_with_a_position_is_rejected(self):
        # Written by the curand-host-generator implementation: no stream tag.
        seed, device, _, _, *engine = jt.Generator("cuda").manual_seed(5).get_state().split(" ")
        with self.assertRaisesRegex(RuntimeError, "older Jittor"):
            jt.Generator("cuda").set_state(" ".join([seed, device, "4096"] + engine))

    def test_old_cpu_state_still_restores(self):
        current = jt.Generator("cpu").manual_seed(5).get_state().split(" ")
        old_format = " ".join(current[:3] + current[4:])
        g = jt.Generator("cpu")
        g.set_state(old_format)
        with jt.flag_scope(use_cuda=0):
            np.testing.assert_array_equal(
                jt.random((10,), generator=g).numpy(),
                jt.random((10,), generator=jt.Generator("cpu").manual_seed(5)).numpy())


if __name__ == "__main__":
    unittest.main()
