// ***************************************************************
// Copyright (c) 2023 Jittor. All Rights Reserved.
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.
// ***************************************************************
// Independent, device-native stateful RNG generators, aligned with
// torch.Generator's contract --
//   - two generators seeded identically produce identical sequences
//   - interleaved draws from different generators never share state
//   - CPU/CUDA sampling happens natively (no NumPy host round-trip),
//     honoring the requested dtype
//   - state is get/set-able for save/restore across runs
//
// Design: each Generator wraps a `shared_ptr<RandomGeneratorState>`. The
// state -- not the pyjt-visible Generator wrapper -- is what RandomOp/
// CurandRandomOp capture (by copying the shared_ptr) at construction time,
// so a lazily-scheduled op keeps the state alive for as long as IT still
// needs it, independent of whatever happens to the Python-side Generator
// object's own refcount in the meantime.
//
// CUDA draws from a generator are counter-based: element positions in one
// Philox4x32-10 stream keyed by the seed, generated by jittor's own kernel
// (backends/cuda/kernels/curand/curand_random_op.cc) through the curand
// *device* API. (seed, position) is therefore the complete CUDA state, and a
// draw's positions are reserved when the op is built, not when it runs. The
// curand host API cannot provide this contract: its generators, XORWOW and
// Philox alike, do not continue a stream across calls the way a fresh
// generator at the summed offset does (e.g. Philox after draws of 5 and 7
// values, or any double draw of about 2^20 values), so a (seed, offset)
// checkpoint of a host generator does not replay.
#pragma once
#include "core/common.h"
#include "core/types.h"
#include <random>

namespace jittor {

struct RandomGeneratorState {
    int64 seed_;
    int device_id; // -1 = cpu, >=0 = cuda device ordinal
    std::default_random_engine cpu_engine;
    // Next unreserved position in this generator's CUDA Philox stream, in
    // 32-bit raw values. Advanced by reserve_cuda() at op construction.
    int64 cuda_offset = 0;

    RandomGeneratorState(int64 seed, int device_id);
    void set_seed(int64 seed);
    // Reserves `raw_count` positions for one draw and returns its first
    // position. Called when the draw is built, so get_state() already covers
    // every draw issued before it, executed or not.
    int64 reserve_cuda(int64 raw_count);

    // Serializes cpu_engine's full state (via the standard <random> stream
    // operators) plus seed/device_id/cuda_offset into an opaque byte string.
    string get_state();
    // Parses and validates everything before changing anything. A state for
    // a different device is rejected (the two carry different streams).
    void set_state(const string& s);
};

// @pyjt(Generator)
// @attrs(heaptype)
struct RandomGenerator {
    shared_ptr<RandomGeneratorState> state;
    string device_str;

    // @pyjt(__init__)
    RandomGenerator(const string& device="cpu");

    // @pyjt(manual_seed)
    // @attrs(return_self)
    RandomGenerator* manual_seed(int64 seed);

    // torch.Generator.seed(): reseed from fresh (unpredictable) entropy and
    // return the new seed.
    // @pyjt(seed)
    int64 reseed();

    // @pyjt(initial_seed)
    int64 initial_seed();

    // @pyjt(get_state)
    string get_state();

    // @pyjt(set_state)
    // @attrs(return_self)
    RandomGenerator* set_state(const string& s);

    // @pyjt(__get__device)
    string get_device();
};

} // jittor
